# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Interception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Copie'), ('2', 'Interception')], max_length=1, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('character_name', models.CharField(max_length=10, verbose_name='Nom du personnage')),
            ],
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5, verbose_name='Lettre')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
            ],
        ),
        migrations.AddField(
            model_name='interception',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='murder.Joueur'),
        ),
        migrations.AddField(
            model_name='interception',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='murder.Joueur'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder.Joueur'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='piste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murder.Piste'),
        ),
    ]
