# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='character_name',
            field=models.CharField(max_length=30, verbose_name='Nom du personnage'),
        ),
    ]
