# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murder', '0002_auto_20180815_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='interception',
            name='done',
            field=models.NullBooleanField(default=False, verbose_name='termine'),
        ),
        migrations.AddField(
            model_name='interception',
            name='resultat',
            field=models.CharField(choices=[('0', 'Reussi'), ('1', 'Rate'), ('2', 'Rate, cible au courant')], max_length=1, null=True, verbose_name='Resultat'),
        ),
    ]
