# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murder', '0003_auto_20180815_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interception',
            name='resultat',
            field=models.CharField(blank=True, choices=[('0', 'Reussi'), ('1', 'Rate'), ('2', 'Rate, cible au courant')], max_length=1, null=True, verbose_name='Resultat'),
        ),
        migrations.AlterUniqueTogether(
            name='enquete',
            unique_together=set([('joueur', 'piste')]),
        ),
    ]
