# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murder', '0006_remove_interception_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_origin', to='murder.Joueur')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_target', to='murder.Joueur')),
            ],
        ),
    ]
